Run `npx typesync; yarn` to ensure we have the correct types
I did this because when I ran `yarn bootstrap && yarn test`, I saw this
error:
```
@statechannels/native-utils:     tests/hash.test.ts:248:3 - error TS2582: Cannot find name 'test'. Do you need to install type definitions for a test runner? Try `npm i @types/jest` or `npm i @types/mocha`.
```